development:
  adapter: postgresql
  encoding: unicode
  database: sandspit-designs_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: sandspit-designs_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sandspit-designs
  pool: 5
